// Generated by CoffeeScript 1.9.2
var Q, SID, client, csv, env, numbers, originNumber, prompt, sendGroupText, sendText, startPrompt, token, twilio;

csv = require('fast-csv');

prompt = require('prompt');

Q = require('q');

twilio = require('twilio');

env = require('node-env-file');

env(__dirname + '/.env');

SID = process.env.SID;

token = process.env.token;

originNumber = process.env.originNumber;

client = new twilio.RestClient(SID, token);

if (process.argv.length !== 3) {
  return console.log('Usage: node send.js [phone.csv]');
}

numbers = [];

csv.fromPath(process.argv[2]).on("data", function(data) {
  return numbers.push(data);
}).on("end", function() {
  return prompt.start();
});

sendText = function(promises, text, number) {
  var q;
  number = "+" + number;
  q = client.sendMessage({
    to: number,
    from: originNumber,
    body: text
  })["catch"](function(err) {
    return console.log("ERROR SENDING " + text + " TO " + number);
  }).then(function(response) {
    return console.log("SENT " + response.body + " TO " + response.to);
  });
  return promises.push(q);
};

sendGroupText = function(text) {
  var i, len, number, promises;
  promises = [];
  for (i = 0, len = numbers.length; i < len; i++) {
    number = numbers[i];
    sendText(promises, text, number);
  }
  return Q.all(promises);
};

startPrompt = function() {
  return prompt.get(['text'], function(err, result) {
    if (err) {
      return console.log("ERROR in prompt");
    }
    return sendGroupText(result.text).then(function() {
      return startPrompt();
    });
  });
};

console.log("Welcome to group text sender! Type in the text you'd like to send to the numbers listed in " + process.argv[2] + " below. Please wait for the prompt before attempting to send another message. ^c to exit.");

startPrompt();
